[package]
name = "gluster"
description = "A library to interface with Gluster's CLI.  This is being leveraged by a Juju charm to manage a Gluster deployment"
documentation = "https://cholcombe973.github.io/Gluster/gluster/index.html"
version = "0.8.1"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
repository = "https://github.com/cholcombe973/Gluster"
license = "MIT"

[dependencies]
byteorder = "~1.2"
log = "~0.3"
regex = "~0.1"
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"
serde-xml-rs = "~0.2"
unix_socket = "~0.5"
uuid = {version = "~0.5", features = ["v4", "use_std", "serde"]}
